config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end
  def new
    @article = Article.new
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path(@articles), status: :see_other
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to articles_path(@articles), status: :see_other
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    # raise
    @article = Article.find(params[:id])
    # @Article.update(Article_params)
    if @article.update(article_params)
      redirect_to articles_path
    else
      render :edit_article
    end
  end

  def show
    @article = Article.find(params[:id])
    # raise
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<h1>Editing article</h1>
<%= form_for(@article) do |f| %>
<div class="card">
  <div class="card-body">
   <div class="mb-3">
  <%= f.label :title %>
  <%= f.text_field :title %>
   </div>

  <br>
   <div class="mb-3">
  <%= f.label :content %>
  <%= f.text_area :content %>
   </div>
  <%= f.submit class: "btn btn-primary"%>
    </div>
</div>
<% end %>
<%= link_to "back", articles_path %>
<%= link_to "show", article_path %>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
<h2><%= link_to article.title, article_path(article) %></h2>
<p><%= article.content %></p>
<% end %>

app/views/articles/show.html.erb
<div>
<h2><%= @article.title %></h2>

<%= link_to edit_article_path, class: 'nav-btn' do %>
    <i class="fa-regular fa-pen-to-square"></i>
<% end %>

<%= link_to article_path(@article), class: 'nav-btn', data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
    <i class="fa-solid fa-trash"></i>
<% end %>

</div>
<h2><%= @article.content %></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>